# Generated by Django 3.2.2 on 2021-10-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_cliente_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_problema', models.CharField(max_length=50)),
                ('desc_solucion', models.CharField(max_length=50)),
                ('nivel', models.PositiveSmallIntegerField(default=0)),
                ('solucionado', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleado')),
            ],
        ),
    ]
