# Generated by Django 3.2.7 on 2021-10-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
