# Generated by Django 3.2.2 on 2021-10-21 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_alter_ticket_solucionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cod_cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
