# Generated by Django 3.2.2 on 2021-10-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_cliente_cod_plan'),
        ('tickets', '0005_auto_20211021_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cod_vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleado'),
        ),
    ]
