# Generated by Django 3.2.2 on 2021-10-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_cod_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='desc_problema',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='desc_solucion',
            field=models.CharField(max_length=350),
        ),
    ]
