# Generated by Django 3.2.2 on 2021-10-09 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nom_usuario',
        ),
    ]
