# Generated by Django 3.2.2 on 2021-10-15 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20211008_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_empleado', models.PositiveSmallIntegerField(default=0)),
                ('cod_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_plan', models.PositiveSmallIntegerField(default=0)),
                ('cod_tipo_tarjeta', models.PositiveSmallIntegerField(default=0)),
                ('num_tarjeta', models.TextField(max_length=50)),
                ('cvv', models.TextField(max_length=50)),
                ('cod_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
