# Generated by Django 3.2.7 on 2021-10-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cod_tipo_tarjeta',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='num_tarjeta',
        ),
        migrations.AddField(
            model_name='cliente',
            name='has_plan',
            field=models.BooleanField(default=False),
        ),
    ]
