# Generated by Django 3.2.2 on 2021-10-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20211017_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cod_plan',
        ),
    ]
