# Generated by Django 3.2.2 on 2021-10-18 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_auto_20211017_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plan', models.CharField(max_length=50)),
                ('valor_plan', models.PositiveSmallIntegerField(default=0)),
                ('cant_dominios', models.PositiveSmallIntegerField(default=0)),
                ('cant_correos', models.PositiveSmallIntegerField(default=0)),
                ('capacidad', models.PositiveSmallIntegerField(default=0)),
                ('hasSSL', models.BooleanField()),
                ('cant_db', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.PositiveSmallIntegerField(default=0)),
                ('fecha_facturacion', models.DateField(auto_now=True)),
                ('fecha_cancelacion', models.DateField()),
                ('cod_cliente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.cliente')),
                ('cod_plan', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.plan')),
            ],
        ),
    ]
