# Generated by Django 3.2.2 on 2021-10-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='periodo_fact',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
