# Generated by Django 3.2.2 on 2021-10-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_plan_periodo_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='fecha_cancelacion',
            field=models.DateField(null=True),
        ),
    ]
