# Generated by Django 3.2.2 on 2021-10-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_cliente_cod_plan'),
        ('pagos', '0004_facturacion_dominios_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='cod_cliente',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='cod_plan',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.plan'),
        ),
    ]
