# Generated by Django 3.2.2 on 2021-10-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_facturacion_esta_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='fecha_facturacion',
            field=models.DateField(),
        ),
    ]
