# Generated by Django 3.2.2 on 2021-10-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_alter_facturacion_fecha_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='fecha_facturacion',
            field=models.DateField(null=True),
        ),
    ]
