# Generated by Django 3.2.2 on 2021-10-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_alter_facturacion_fecha_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='esta_activo',
            field=models.BooleanField(),
        ),
    ]
