# Generated by Django 3.2.7 on 2021-10-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_alter_plan_valor_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='valor_total',
            field=models.IntegerField(default=0),
        ),
    ]
