# Generated by Django 3.2.7 on 2021-10-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_alter_facturacion_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='cod_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.plan'),
        ),
    ]
