# Generated by Django 3.2.2 on 2021-10-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('usuario_realiza', models.CharField(max_length=20)),
                ('area_afectada', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
