# Generated by Django 3.2.2 on 2021-10-19 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0003_alter_facturacion_fecha_cancelacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaDistribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categoria', models.CharField(max_length=50)),
                ('porcentaje_ganancia', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_distribuidor', models.CharField(max_length=50)),
                ('cod_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dominios.categoriadistribuidor')),
            ],
        ),
        migrations.CreateModel(
            name='dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dominio', models.CharField(max_length=50)),
                ('link_dominio', models.CharField(max_length=50)),
                ('cod_distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dominios.distribuidor')),
                ('cod_facturacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.facturacion')),
            ],
        ),
    ]
