# Generated by Django 3.2.2 on 2021-10-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='cod_distribuidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dominios.distribuidor'),
        ),
    ]
