# Generated by Django 3.2.2 on 2021-10-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0002_alter_dominio_cod_distribuidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='cod_distribuidor',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
